version: '3'
services:

    #nginx
        nginx:
            build: ./nginx
            container_name: books-nginx
            ports: 
                - 80:80
            links:
                - node1:node1
                - node2:node2
                - node3:node3
            volumes:
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    # Back-end
        node1:
            image: node
            container_name: books-api1
            ports:
                - 3000
            volumes:
                - ./books-backend/app:/app
                - ./books-backend/app.js:/app.js
                - ./books-backend/config.js:/config.js
                - ./books-backend/package.json:/package.json
                - ./books-backend/package_lock.json:/package_lock
                - ./books-backend/test.js:/test.js
            links:
                - mongodb
            command: bash -c "npm install && npm start"

        node2:
            image: node
            container_name: books-api2
            ports:
                - 3000
            volumes:
                - ./books-backend/app:/app
                - ./books-backend/app.js:/app.js
                - ./books-backend/config.js:/config.js
                - ./books-backend/package.json:/package.json
                - ./books-backend/package_lock.json:/package_lock
                - ./books-backend/test.js:/test.js
            links:
                - mongodb
            command: bash -c "npm install && npm start"

        node3:
            image: node
            container_name: books-api3
            ports:
                - 3000
            volumes:
                - ./books-backend/app:/app
                - ./books-backend/app.js:/app.js
                - ./books-backend/config.js:/config.js
                - ./books-backend/package.json:/package.json
                - ./books-backend/package_lock.json:/package_lock
                - ./books-backend/test.js:/test.js
            links:
                - mongodb
            command: bash -c "npm install && npm start"


    # MongoDB
        mongodb:
            build: ./db
            container_name: books-mongo
            ports:
                - 27017
            volumes:
                - ./db/mongo:/data/db
